

spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration  
  mvc:
    favicon:
      enabled: false
      
my:
  feature-enabled: true
  range: 100       